# Generated by Django 5.2.7 on 2025-10-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('poblacion', models.IntegerField()),
                ('lugares_turisticos', models.TextField(help_text='Separados por comas')),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
