# Generated by Django 5.2.7 on 2025-11-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='lugares_turisticos',
            field=models.CharField(max_length=255),
        ),
    ]
